### ISSUE TITLE
Parse comments into tree

### ISSUE THREAD

**Issue by gregor-ge** [ErikBird/OpenReviewCrawler#8]
Eine Funktion wäre nicht schlecht, die Notes nimmt und daraus den Kommentarbaum macht. Wird für 2B hilfreich sein vermutlich.
Außerdem sind aktuell Kommentare, Reviews, Autor Kommentare etc in eigenen Invitations. Bei einem Baum hat man die dann zusammen.

**Comment by acid-horny** [comment]
Funktion umschreiben, json nachträglich umformen
